{{- if .Values.operator.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hortator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hortator.labels" . | nindent 4 }}
  {{- with .Values.operator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
