{{- if and .Values.webhook .Values.webhook.enabled }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "hortator.fullname" . }}-validating-webhook
  labels:
    {{- include "hortator.labels" . | nindent 4 }}
  {{- if and .Values.webhook.certManager .Values.webhook.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "hortator.fullname" . }}-webhook-cert
  {{- end }}
webhooks:
  - name: vagenttask.kb.io
    admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "hortator.fullname" . }}-webhook
        namespace: {{ .Release.Namespace }}
        path: /validate-core-hortator-ai-v1alpha1-agenttask
        port: {{ .Values.webhook.port | default 9443 }}
    failurePolicy: Fail
    rules:
      - apiGroups:
          - core.hortator.ai
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - agenttasks
    sideEffects: None
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hortator.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hortator.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.webhook.port | default 9443 }}
      targetPort: webhook
      protocol: TCP
      name: webhook
  selector:
    {{- include "hortator.selectorLabels" . | nindent 4 }}
{{- if and .Values.webhook.certManager .Values.webhook.certManager.enabled }}
---
{{- if not .Values.webhook.certManager.issuerName }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "hortator.fullname" . }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hortator.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "hortator.fullname" . }}-webhook-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hortator.labels" . | nindent 4 }}
spec:
  dnsNames:
    - {{ include "hortator.fullname" . }}-webhook.{{ .Release.Namespace }}.svc
    - {{ include "hortator.fullname" . }}-webhook.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: {{ .Values.webhook.certManager.issuerKind | default "Issuer" }}
    name: {{ .Values.webhook.certManager.issuerName | default (printf "%s-selfsigned-issuer" (include "hortator.fullname" .)) }}
  secretName: {{ include "hortator.fullname" . }}-webhook-tls
{{- end }}
{{- end }}
